name: PanditBOT 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Setup Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5 #install the python needed
    - name: Updating README.md
      run: |
          python add.py
          git config user.name PtPrashantTripathi
          git config user.email ptprashanttripathi@outlook.com
          git add .
          git commit -m "Updating README.md"
          git push --quiet
